services:
  app:
    image: fireflyiii/core:version-6.6.6
    hostname: app
    container_name: firefly_iii_core
    restart: always
    volumes:
      - /mnt/nas/prod/firefly/core:/var/www/html/storage/upload
    networks:
      - firefly_iii
      - proxy
    depends_on:
      - db
    environment:
      APP_ENV: "production"
      APP_DEBUG: "false"
      SITE_OWNER: ${SITE_OWNER}
      APP_KEY: ${APP_KEY}
      DEFAULT_LANGUAGE: "en_US"
      DEFAULT_LOCALE: "equal"
      TZ: "Europe/Oslo"
      TRUSTED_PROXIES: "**"
      LOG_CHANNEL: "stack"
      APP_LOG_LEVEL: "notice"
      AUDIT_LOG_LEVEL: "emergency"
      DB_CONNECTION: "mysql"
      DB_HOST: "db"
      DB_PORT: 3306
      DB_DATABASE: "firefly"
      DB_USERNAME: "firefly"
      DB_PASSWORD: ${DB_PASSWORD}
      MYSQL_USE_SSL: "false"
      MYSQL_SSL_VERIFY_SERVER_CERT: "true"
      MYSQL_SSL_CAPATH: "/etc/ssl/certs/"
      PGSQL_SSL_MODE: prefer
      PGSQL_SSL_ROOT_CERT: "null"
      PGSQL_SSL_CERT: "null"
      PGSQL_SSL_KEY: "null"
      PGSQL_SSL_CRL_FILE: "null"
      PGSQL_SCHEMA: public
      CACHE_DRIVER: file
      SESSION_DRIVER: file
      REDIS_SCHEME: tcp
      REDIS_HOST: 127.0.0.1
      REDIS_PORT: 6379
      REDIS_DB: "0"
      REDIS_CACHE_DB: "1"
      COOKIE_PATH: "/"
      COOKIE_SECURE: "false"
      COOKIE_SAMESITE: lax
      MAIL_MAILER: log
      MAIL_HOST: "null"
      MAIL_PORT: 2525
      MAIL_FROM: "changeme@example.com"
      MAIL_USERNAME: "null"
      MAIL_PASSWORD: "null"
      MAIL_ENCRYPTION: "null"
      MAIL_ALLOW_SELF_SIGNED: "false"
      MAIL_VERIFY_PEER: "true"
      MAIL_VERIFY_PEER_NAME: "true"
      MAILGUN_ENDPOINT: api.mailgun.net
      SEND_ERROR_MESSAGE: "true"
      MAP_DEFAULT_LAT: 51.983333
      MAP_DEFAULT_LONG: 5.916667
      MAP_DEFAULT_ZOOM: 6
      AUTHENTICATION_GUARD: web
      AUTHENTICATION_GUARD_HEADER: REMOTE_USER
      DISABLE_FRAME_HEADER: "false"
      DISABLE_CSP_HEADER: "false"
      DKR_CHECK_SQLITE: "true"
      APP_NAME: FireflyIII
      BROADCAST_DRIVER: log
      QUEUE_DRIVER: sync
      CACHE_PREFIX: firefly
      FIREFLY_III_LAYOUT: v1
      APP_URL: ${APP_URL}
      STATIC_CRON_TOKEN: ${STATIC_CRON_TOKEN}
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.financial.rule=Host(`money.jonasandersen.dev`)
        - traefik.http.services.financial.loadbalancer.server.port=8080
        - traefik.http.routers.financial.entrypoints=http,https
  db:
    image: mariadb:lts
    user: "999:999"
    hostname: db
    container_name: firefly_iii_db
    restart: always
    networks:
      - firefly_iii
    volumes:
      - /mnt/nas/prod/firefly/db:/var/lib/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: yes
      MYSQL_USER: firefly
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: firefly
  cron:
    #
    # To make this work, set STATIC_CRON_TOKEN in your .env file or as an environment variable
    # The STATIC_CRON_TOKEN must be *exactly* 32 characters long
    # Use this URL for inspiration: https://www.random.org/strings/?num=1&len=32&digits=on&upperalpha=on&loweralpha=on&unique=on&format=html&rnd=new
    #
    image: alpine
    restart: always
    container_name: firefly_iii_cron
    environment:
      STATIC_CRON_TOKEN: ${STATIC_CRON_TOKEN}
    command: ["sh", "-c", "apk add tzdata && \
      (ln -s /usr/share/zoneinfo/$$TZ /etc/localtime || true) && \
      echo \"0 3 * * * wget -qO- http://app:8080/api/v1/cron/$$STATIC_CRON_TOKEN;echo\" \
      | crontab - && \
      crond -f -L /dev/stdout"]
    networks:
      - firefly_iii
    depends_on:
      - app

networks:
  proxy:
    external: true
  firefly_iii:
    driver: overlay
    attachable: true
